{{- if not .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.configToken" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  otterdog_config_token: {{ .Values.config.configToken | default "" | trim | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.webhookSecret" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  github_webhook_secret: {{ .Values.github.webhookSecret | default "" | trim | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.appPrivateKey" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  github_app_key: {{ .Values.github.appPrivateKey | default "" | trim | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.dependencyTrackToken" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  dependency_track_token: {{ .Values.config.dependencyTrackToken | default "" | trim | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.mongoUri" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongo_uri: {{ include "otterdog.mongodb.uri" . }}
{{- if .Values.mongodb.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb-root-credentials" (include "webapp.fullname" .) }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb_root_username: {{ .Values.mongodb.auth.rootUsername | default "root" | trim }}
  mongodb_root_password: {{ .Values.mongodb.auth.rootPassword | default "" | trim }}
{{- end }}
---
{{- $user := include "otterdog.mongodb.firstUser" . | fromJson }}
{{- if get $user "name" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mongodb-app-credentials" (include "webapp.fullname" .) }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  CUSTOM_USER: {{ get $user "name" }}
  CUSTOM_PASSWORD: {{ coalesce (get $user "password") .Values.config.mongoPassword "" | trim }}
  CUSTOM_DB: {{ include "otterdog.mongodb.database" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterdog.secret.redisUri" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis_uri: {{ include "otterdog.valkey.uri" . }}
{{- end }}
