# config.configToken
{{- if .Values.config.configToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: config-token-secret
type: Opaque
data:
  token: {{ .Values.config.configToken | quote }}
{{- end }}
# config.webhookSecret
{{- if .Values.github.webhookSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
type: Opaque
data:
  secret: {{ .Values.github.webhookSecret | quote }}
{{- end }}
# config.appPrivateKey
{{- if .Values.github.appPrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-private-key
type: Opaque
data:
  privateKey: {{ .Values.github.appPrivateKey | quote }}
{{- end }}
# config.dependecyTrackToken
{{- if .Values.config.dependecyTrackToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dependency-track-token-secret
type: Opaque
data:
  token: {{ .Values.config.dependecyTrackToken | quote }}
{{- end }}
