#
#  *******************************************************************************
#  Copyright (c) 2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************
#
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "helm" 
    directory: "/charts/otterdog/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "deps-helm"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"