#
#  *******************************************************************************
#  Copyright (c) 2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************
#
apiVersion: v2
name: otterdog
description: An otterdog Web App Helm chart for Kubernetes
maintainers:
  - name: eclipse-csi
type: application
version: 1.1.4
appVersion: "1.1.0"
dependencies:
  - name: ghproxy
    version: 0.2.0
    repository: "https://eclipse-csi.github.io/helm-charts"
    condition: ghproxy.enabled
