#
#  *******************************************************************************
#  Copyright (c) 2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************
#
apiVersion: v2
name: otterdog
description: An otterdog Web App Helm chart for Kubernetes
maintainers:
  - name: eclipse-csi
type: application
version: 1.0.1
appVersion: "1.0.2"
dependencies:
  - name: mongodb
    version: 16.5.4
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: valkey
    version: 3.0.3
    repository: "https://charts.bitnami.com/bitnami"
    condition: valkey.enabled
  - name: ghproxy
    version: 0.1.0
    repository: "https://eclipse-csi.github.io/helm-charts"
    condition: ghproxy.enabled
