{{- if not .Values.vault.enabled }}
{{- if .Values.redisPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghproxy.fullname" . }}-redis-auth
  labels:
    {{- include "ghproxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redisPassword }}
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}