apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghproxy.fullname" . }}
  labels:
    {{- include "ghproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    {{- include "ghproxy.selectorLabels" . | nindent 4 }}
