{{- if or (and .Values.config.dependencyTrackApiKey (not .Values.config.dtApiExistingSecret)) (and .Values.config.databaseUrl (not .Values.config.dbExistingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pia.fullname" . }}-secret
  labels:
    {{- include "pia.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.config.dependencyTrackApiKey (not .Values.config.dtApiExistingSecret) }}
  PIA_DEPENDENCY_TRACK_API_KEY: {{ .Values.config.dependencyTrackApiKey | quote }}
  {{- end }}
  {{- if and .Values.config.databaseUrl (not .Values.config.dbExistingSecret) }}
  PIA_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  {{- end }}
{{- end }}
